site_name: Android MCP SDK
site_description: An Android library that integrates the MCP Kotlin SDK to enable Android applications to host MCP (Model Context Protocol) servers.
site_author: Jason Pearson
site_url: https://kaeawc.github.io/android-mcp-sdk/
repo_name: kaeawc/android-mcp-sdk
repo_url: https://github.com/kaeawc/android-mcp-sdk
edit_uri: edit/main/docs/

copyright: 'Copyright &copy; 2025 Jason Pearson'

theme:
  name: material
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue
      accent: blue
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/weather-night
        name: Switch to light mode
  features:
    - content.code.annotate
    - content.code.copy
    - content.tabs.link
    - navigation.footer
    - navigation.indexes
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - search.highlight
    - search.suggest
    - toc.follow
  icon:
    repo: fontawesome/brands/github
    edit: material/pencil
    view: material/eye

extra:
  social:
    - icon: fontawesome/emojis/nerd-face
      link: https://www.jasonpearson.dev
    - icon: fontawesome/brands/github
      link: https://github.com/kaeawc
    - icon: fontawesome/brands/bluesky
      link: https://bsky.app/@kaeawc
    - icon: fontawesome/brands/linkedin-in
      link: https://linkedin.com/in/jasondpearson

markdown_extensions:
  - admonition
  - attr_list
  - codehilite:
      guess_lang: false
  - footnotes
  - md_in_html
  - meta
  - pymdownx.betterem
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - tables
  - toc:
      permalink: true

plugins:
  - search
  - minify:
      minify_html: true
  - git-revision-date-localized:
      enable_creation_date: true

nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - Usage Guide: usage.md
  - ADB Port Forwarding: adb-port-forwarding.md
  - Transport Configuration: transport.md
  - API Reference: api-reference.md
  - Implementation:
      - Implementation Summary: ai/implementation-summary.md
      - Validation Rules: ai/validation.md
  - Development:
      - Roadmap: ../roadmap/README.md
  - Documentation:
      - Complete MCP Server Wrapper: COMPLETE_MCP_SERVER_WRAPPER.md
